config/routes.rb
Rails.application.routes.draw do

    root 'products#index'
    get 'products/index'

    resources :products do
      resources :reviews
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews

  validates :name, :description, :price_in_cents, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  def price_in_dollars
  price_in_dollars = price_in_cents.to_f / 100
  sprintf("$%.2f", price_in_dollars)
  end



end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :comment, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new

    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]

    if @product.save
      flash[:notice] = "Product successfully created"
      redirect_to '/products'

    else
      render :new
    end

  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully deleted"
    redirect_to products_path
  end

  def update
    @product = Product.find(params[:id])
      if @product.update(product_params)
        flash[:notice] = "Product successfully updated"
        redirect_to @product
      else
        redirect_back_or_to @product
      end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def index
    @product = Product.find(params[:product_id])
    @review = Review.all
    render product_reviews_path
  end

 def show
   @product = Product.find(params[:product_id])
   @review = Review.find(params[:id])
   render :show
 end

def edit
  @product = Product.find(params[:product_id])
  @review = Review.find(params[:id])
end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    @review.comment = params[:review][:comment]

    if @review.save
      flash[:notice] = "Review successfully created"
      redirect_to products_path

    else
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(comment: params[:review][:comment])
      flash[:notice] = "You have successfully updated a review."
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Inconsolata" rel="stylesheet">
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "New Product", new_product_path %></li>
      </ul>
    </nav>

    <%= yield %>


    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
  </body>
</html>

app/views/products/_product_form.html.erb
<%= form_for @product do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :description %>
  <%= f.text_field :description %>
</p>

<p>
  <%= f.label :price_in_cents %>
  <%= f.text_field :price_in_cents %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/products/_single_product.html.erb
<div class="single_product">
  <h3>Name: <%= @product.name %> </h3>
  <p>Description: <%= @product.description %></p>
  <p>Price: <%= @product.price_in_dollars %></p>
</div>

app/views/products/edit.html.erb
<h1>Editing <%= link_to @product.name, product_path(@product) %> </h1>
<%= render 'product_form', single_product: @product %>

app/views/products/index.html.erb
<div class="showpage">


<h1>Products</h1>
<div class="newproductbutton">
<%= link_to("New Product", "/products/new") %>
</div>



<% @products.each do |product| %>
<div class="eachproduct">
<p><%= product.name %> | <%= product.description %> | <%= product.price_in_dollars %></p>
<p>Reviews: <%= product.reviews.count %></p>
<%= link_to("Show More", "/products/#{product.id}") %>
</div>
<% end %>



</div>

app/views/products/new.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this item from being saved:</h2>

   <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @product do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :description %>
  <%= f.text_field :description %>
</p>

<p>
  <%= f.label :price_in_cents %>
  <%= f.text_field :price_in_cents %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<%= render 'single_product', single_product: @product %>

<%= link_to 'Edit', edit_product_path %> |
<%= link_to 'Delete', product_path(@product), method: :delete, data: {confirm: "Are you sure you want to delete the product '#{@product.name}'? This cannot be undone!"} %>

<h2>Reviews</h2>
<% @product.reviews.each do |review|%>
<ul>
  <li><%= review.comment %></li>
</ul>
<% end %>

<h4>Add a review</h4>

<%= render '/reviews/form', product: @product %>

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_single_review.html.erb
<%= form_for @review do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :comment %>
  <%= f.text_field :comment %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit your review</h1>
<%= render '/reviews/form', product: @product %>

<%= link_to("Delete", product_review_path(@product.id,@review.id), method: :delete, data: {confirm: "Are you sure you want to delete your review?"})  %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<% @product.reviews.each do |review|%>
<ul>
  <li><%= review.comment %></li>
</ul>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews</h1>

<% @product.reviews.each do |review|%>
<ul>
  <li><%= review.comment %></li>
</ul>
<% end %>